### ISSUE TITLE
Readonly acl setup

### ISSUE THREAD

**Issue by sreekesh93** [IBM/docker-prestodb#22]
Hi,
 I am trying to use this image to run presto and i want to set up readonly acl, to enable acl i need to create an access_control.properties in etc folder. To create file i dont have permission. How to achieve the same?

**Comment by shawnzhu** [comment]
@sreekesh93 Good question! So the idea is don't change but mount/bind a file when creating a container from it. For example:

```SHELL
$ echo "access-control.name=read-only > access-control.properties"
$ docker run -d \
 -p 8080:8080 \
 --name presto_acl_test \
 -v $(pwd)/access-control.properties:/home/presto/etc/access-control.properties \ shawnzhu/prestodb:latest
$ docker exec -it 9e32ad0bb06f cat /home/presto/etc/access-control.properties
access-control.name=read-only
```
